version: "3.4"

services:
  webserver:
    build:
      context: _docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/app
    depends_on:
      - fpm
      - mysql
    links:
      - mysql
    ports:
      - '80:80'
      - '443:443'

  fpm:
    build:
      context: _docker
      dockerfile: fpm.dockerfile
    volumes:
      - ./:/app
    environment:
      XDEBUG_IDE_KEY: "PHPSTORM"
      XDEBUG_REMOTE_HOST: "192.167.220.1"
      PHP_IDE_CONFIG: "serverName=Docker"
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql
    depends_on:
      - mysql

  cli:
    build:
      context: _docker
      dockerfile: cli.dockerfile
    volumes:
      - ./:/app
    depends_on:
      - mysql
    tty: true
    environment:
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql

  mysql:
    image: mariadb:10.6.4
    restart: always
    volumes:
    - ./_docker/mysql/my.cnf:/etc/mysql/my.cnf
    - ./_docker/sql-backup:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
    - "82:80"
    volumes:
      - /sessions
    environment:
      - "PMA_ARBITRARY=1"
      - "PMA_HOST=mysql"
      - "PMA_PORT=3306"

  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    command: mongod

